import './globals.css';
import type { Metadata } from 'next';
import NavMenu from './components/NavMenu'; // подключаем наше меню

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        <NavMenu /> {/* Меню будет на всех страницах */}
        {children}
      </body>
    </html>
  );
}
